### ISSUE TITLE
Implement www.isotc154.org website

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/www.isotc154.org#1]
Similar to ISO/TC 211's website, we are going to migrate ISO/TC 154's website.

This website used to exist but has since disappeared. The old version can be still seen on Archive.org.
http://web.archive.org/web/20161023122129/http://www.isotc154.org/minutes

I have been able to extract the old site information (not completely) into this repo.

The work is to convert all this data into AsciiDoc (I've done some), and make it into a Jekyll site just like the ISO/TC 211 site.

@strogonoff do you have time for this? Thanks!

**Comment by strogonoff** [comment]
@ronaldtse  Yes, deployed the big Metanorma update, starting with ISO TC 211 (and now also ISO TC 154) websites

**Comment by strogonoff** [comment]
I thought we’ll have a TC-specific theme and put TC 211 in the name. Caught by surprise that we’ll be dealing with more TCs. Not that it’s an issue, I’ll see if jekyll-theme-isotc211 layout works with TC 154 and might rename theme gem to something more generic if so.

**Comment by strogonoff** [comment]
Somehow the archived version looks a bit suspicious in places 😂

<img width="1552" alt="screen shot 2019-02-17 at 11 19 31 am" src="https://user-images.githubusercontent.com/292959/52907904-00269800-32a6-11e9-912b-fda16ee589ee.png">

**Comment by ronaldtse** [comment]
Indeed -- I think the Wordpress site was hijacked before it went offline. The images have been properly retrieved though (in the repo).

**Comment by ronaldtse** [comment]
Regarding the theme, we will probably have a different design for 154, so it won't hurt either way (based on same gem or new gem).

**Comment by ronaldtse** [comment]
Design for ISO/TC 154

https://invis.io/4PQSI5TJQXE#/349851710_Homepage

![homepage](https://user-images.githubusercontent.com/11865/53691360-67207280-3db7-11e9-802d-ec8a45639027.png)
![minutes](https://user-images.githubusercontent.com/11865/53691361-67207280-3db7-11e9-8711-2f1dafdd7cbc.png)
![project details](https://user-images.githubusercontent.com/11865/53691362-67207280-3db7-11e9-9773-749ceefc2eb3.png)
![projects](https://user-images.githubusercontent.com/11865/53691363-67b90900-3db7-11e9-96a0-6ec90f3bbbc1.png)
![standard details](https://user-images.githubusercontent.com/11865/53691364-67b90900-3db7-11e9-865a-b5b07bda62fa.png)
![standards](https://user-images.githubusercontent.com/11865/53691365-67b90900-3db7-11e9-9c1c-5843b37a24f8.png)

**Comment by ronaldtse** [comment]
@strogonoff , I've cleaned up all the content into AsciiDoc now. Please help proceed with this site. Thanks!

**Comment by ronaldtse** [comment]
@strogonoff actually it's now running on Jekyll -- just need the following:

1. Fix/update nav bar and footer.
2. Move `standards/` `projects/` `minutes/` into `_{name}` so they are treated as collections. Then we can provide indexes for them and individual pages.
3. Implement designs...

Thanks!

**Comment by ronaldtse** [comment]
This site is now recognized by ISO/CS as an official committee site. Closing.
