### ISSUE TITLE
From ISO: Remove/Protect all minutes from TC 154 meetings

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/www.isotc154.org#12]
All TC internal communication, including minutes, are not meant to be shared.

**Comment by strogonoff** [comment]
@ronaldtse  Given target audiences for main site and internal communications are mostly disjoint (presenting info for non-members vs. serving as data source for members of the committee), do you reckon [minutes data](https://github.com/iso-tc154/www.isotc154.org/tree/master/_minutes) warrants a distinct, protected mini-site?

There are some options for how we can handle authentication. If we can’t put it under, say, VPN, then user authentication could be done with a basic dynamic backend or some CF/Lambda magic (possibly with Cognito) for a pseudo-serverless approach.

**Comment by ronaldtse** [comment]
Minutes data does deserve a separate section of the site. We have a lambda function that allows password protection for a certain section (see riboseinc account). If you let me know the path I can set it up.

**Comment by strogonoff** [comment]
@ronaldtse 

I assume this requires moving minutes data to a separate private Git repo.

With that in mind, possible implementations:

1. Submodule minutes data repo inside www.isotc154.org general site public repo. Proceed generating a single site and protect parts of it using Lambda solution.

2. Do not submodule. Generate a separate Jekyll instance from minutes repo, and host it under e.g. a subdomain.

My impression is that we **technically have two sites** with disjoint audiences (members vs. non-members TC) and different UX goals.

Thus I believe solution (2) is proper solution.

Right now the members site only features minutes, but I can foresee how it can facilitate other communications and host more internal data in future.

Solution (1) may be acceptable as a temporary measure though.

**Comment by ronaldtse** [comment]
> I assume this requires moving minutes data to a separate private Git repo.

Yes. Please help create it. 

> My impression is that we technically have two sites with disjoint audiences (members vs. non-members TC) and different UX goals.

> Thus I believe solution (2) is proper solution.

Yes, but we don’t want the TC members to switch between sites, I am quite sure people will complain about it...

**Comment by ronaldtse** [comment]
All minutes have been moved to a separate private repo. Closing this.
