### ISSUE TITLE
Is this a home site or resource index site for ISO TC 154?

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/www.isotc154.org#5]
Belated but fairly fundamental question in the subject.

TC 211 sites are designated as resource sites, including www.isotc211.org, the home site of which is at https://committee.iso.org/home/tc211.

TC 154 home site does not exist at https://committee.iso.org/home/tc154, which makes me think that here we’re creating the home site for the committee rather than just a resource index.

TC home site would have somewhat different requirements compared to a TC resource site. If we know the purpose of the site, we’ll be able to make the theme accommodate that.

**Comment by ronaldtse** [comment]
@strogonoff yes, this is planned to be the home site. We already have a design for it, which I'm sure you know of: https://github.com/iso-tc154/design 😉 

(as you know, we are not looking for 100% identical styling, but whatever that works)

**Comment by ronaldtse** [comment]
@strogonoff this is officially the home site now.
