### ISSUE TITLE
Add "Member" layout

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/www.isotc154.org#7]
https://www.isotc154.org/members/

Right now there's not much of a layout.

**Comment by strogonoff** [comment]
@ronaldtse one member is lacking a photo. Can we count on all members having a photo?

**Comment by ronaldtse** [comment]
Who is the missing photo? I’ll get it.

**Comment by strogonoff** [comment]
@ronaldtse Peter Rybar

**Comment by strogonoff** [comment]
Great, having all photos allows for a nicer layout

**Comment by ronaldtse** [comment]
Not sure if Peter Rybar will provide a photo, but I will follow up.

**Comment by ronaldtse** [comment]
@strogonoff let's assume we can't get a photo from Peter Rybar. Maybe a placeholder could work...

**Comment by strogonoff** [comment]
@ronaldtse implemented members page as a grid with photos and roles. Peter’s photo will be greyed out for now, but we can show something nicer or special-case a no-photo member card layout for Peter.

**Comment by ronaldtse** [comment]
Thanks!
